src/delay.rs

Assert-free delay implemtation from the one by @jamesmunns in the stm32f103xx-hal crate.
The [stm32f103 implementation](https://github.com/japaric/stm32f103xx-hal/blob/master/src/delay.rs#L48).

Assert-free delay implemtation

---

src/serial.rs

This avoid warning about unused imports when compiling for stm32f401.

serial: some GPIO pins are not used on stm32f401

---

src/gpio.rs

The manual states that for output pins, the input data register is still updated with the current signal level.
At least for open-drain outputs, it makes sense to do this (e.g. when bit-banging I2C).
(The same is actually true for alternate-function pins. Can it be useful there too?)

gpio: implement InputPin for output pins

---

src/rcc.rs

This allows configuring the cache bits independent of clock freeze.
An alternative would be to switch the caches on in here?

rcc: keep the cache bits in FLASH_ACR intact

---

Cargo.toml
src/lib.rs

This fixes `cargo publish`.
The last patch may not be the prettiest but it makes some sens anyway.

Allow compiling without any feature selected

---

src/lib.rs
src/spi.rs

I based this off of spi.rs in stm32f103xx-hal. Verified on an F407 with a device and F429 by logic analyzer / loopback.
The SPI4/5/6 block should be left commented until https://github.com/adamgreig/stm32-rs/pull/83 is fully released (next version) and this crate updates to the new version.

SPI: Add support for STM32F4{01,07,12,29}

---

src/spi.rs

This adds SPI 4, 5, and 6 to all chips that support them now that `stm32f4` has the correct RCC bits.

SPI: Add SPI4/5/6 support

---

src/gpio.rs

This change prevents a small blip on the pin when changing to an alternate function. In my case, this was causing an I2C device to not respond. It was jumping to AF0 first, then AF4 a few cycles after.
The following was used to initialize the I2C pins.
```rust
let scl = gpiob.pb6.into_alternate_af4().set_open_drain();
let sda = gpiob.pb9.into_alternate_af4().set_open_drain();
```
Here is evidence of the small blip from before the change. After doesn't have this

Update the GPIO mode register after setting AF

---

src/gpio.rs
src/lib.rs
src/rcc.rs
src/spi.rs
src/timer.rs

This patch series adds support for every existing stm32f4 devices. It is not complete yet. Serial and I2C still needs to be done. Moreover, it requires a new release of the stm32f4 crates for some devices.
Anyway, you may still want to merge the patch series, except for the last patch, which is the one actually enabling all those new devices.

Add support for all existing stm32f4 devices

---

src/i2c.rs

This is a mutation (actually not bad) of my first thought on how to get code reuse of the I2C peripherals without resorting to macros. The bare minimum pins and peripherals were added to get the point across. Currently untested, I have some sort of wiring issue or bad chip to deal with.
The core of this is the fact that I2C1, 2, and 3 all implement `Deref<Target = i2c3::RegisterBlock>`, I'm assuming due to some deduplication (also assuming it lives somewhere in `svd2rust`). If this deduplication will continue to exist in the future, I don't see any negatives associated with it.
Two traits were needed so the `embedded_hal` traits could directly use the `Deref` constraint instead of requiring a new `impl` for each I2C peripheral due to the enable bits and pclk.
Correct me if I'm wrong, but …

Allow reuse of I2C code without macros

---

src/serial.rs

This change came about in my playing with `cortex-m-rtfm` and serial. What I discovered is that once you have the Tx and Rx structs, you can no longer mask and unmask the interrupts of the usart. This breaks common patterns like unmasking `TxE` to send data, then masking it when done transmitting.
This seems to be the more intuitive way as opposed to adding an `impl` of listen and unlisten to Tx and Rx.

Add in serial Read and Write hal implementations for Serial

---

src/lib.rs

This is something I just added to the l4 hal. I found when compiling, If I forgot to add the features I would get confusing error messages about the hal missing modules etc.

Add compile time barrier to make sure a device is chosen.

---

src/i2c.rs
src/lib.rs

This is the last missing piece to have all implemented Traits supported on every stm32f4 devices.

i2c: add support for every stm32f4 devices

---

src/serial.rs

The formula to compute USARTDIV (when OVER8 is 0) is:
USARTDIV = round (f_CK / (16 * baudrate))
As USARTDIV is a fixed point number with 4 bits fractionnal part (when
OVER8 is 0), this simplifies to:
USARTDIV_reg = round (f_CK / baudrate)
The original code was computing the rounded fractionnal part which could
overflow. In this case, it could cause an error of 1 when the mantisa is
odd.

serial: simplify baud rate divisor computation, fix fraction overflow

---

src/i2c.rs
src/serial.rs

Allow mixing different pins for one I2C or USART port in the same way it is done for SPI.
For example, for I2C1, the SCL/SDA pairs PB6/PB7 and PB8/PB9 where define. This PR allows to also use the PB6/PB9 or PB8/PB7 pairs.
For USART it also allows using a TX pin with no RX (or the opposite).

Pins mixing

---

CHANGELOG.md
src/gpio.rs

I've tweaked my recent external interrupt pin implementation to reduce the macro invocation size and cover partially erased pins.
Since the latter know their pin number all the necessary offsets in config registers can be computed.

Gpio exti refactor

---

src/gpio.rs

gpio: fix exticr offset to match the pin num rather than the port num

---

CHANGELOG.md
src/adc.rs
src/lib.rs

Hi,
I've taken a bash at doing an ADC implementation.
It's got embedded_hal::adc::Channel implementations for all VREF, temp sensor and VBAT and of course the GPIO pins. Getting a complete list of all the GPIO and which ADC they are hooked to was a bit of a faff but eventually I used a few grep commands to pull the info out of the CubeMX database files so it should be pretty accurate. CubeMX claims that all STM32F4 devices have the same ADC IP block so it should function the same across all devices this crate supports. 
The current device features aren't sufficient to perfectly identify which GPIO are available because some device variants will have some pins missing or added. However, these are in the minority so I don't think it's worth adding another 10+ features for specific device …

Hal ADC supporting one-shot and sequence conversion of regular channels.

---

CHANGELOG.md
src/lib.rs
src/time.rs
src/watchdog.rs

I've had this in [stm32f429-hal](https://github.com/astro/stm32f429-hal) and now I'm happy to contribute here. There are even improvements like `IndependentWatchdog::stop_on_debug()`. Tested on STM32F429.

Add IWDG Watchdog implementation

---

src/serial.rs

This looks like a mistake to me.

Make is_rxne() borrow rather than consume the serial

---

CHANGELOG.md
src/spi.rs

Extend the SPI API to enable and disable interrupts, and to enable and disable the peripheral alltogether.

Spi interrupt config

---

src/spi.rs

In #82 I added only an accessor for the MODF flag, because I thought it was the only error that could happen using the current API ([see discussion here](https://github.com/stm32-rs/stm32f4xx-hal/pull/82#discussion_r265199725)). However, I just had to find out just know that it is also possible to overrun the SPI by repeatedly calling `send()` without intermediate `read()` calls on the bare `FullDuplex` abstraction (not one of the `Default` blocking implementations from `embedded_hal::blocking::spi{read, write, transfer}).
That's why I added this accessor so users can poll the OVR flag when handling error interrupts. I'm sorry to open a new PR for this, I should have noticed it before.

Accessor for SPI OVR flag

---

CHANGELOG.md
src/lib.rs
src/signature.rs

This data is not a peripheral (hence not in SVDs) but in flash memory.
Example use case: generating unique stable device addresses for network communications.
Should exist across the whole f4xx line.

implement device electronic signature

---

src/adc.rs

adc: reuse signature::VrefCal

---

CHANGELOG.md
src/i2c.rs

This PR is an improved alternative to #91, which contains all the details about this change.

I2C: properly terminate read with a NACK then a STOP

---

CHANGELOG.md
src/spi.rs

With the updates in stm32f4 v0.7.0, we can now apply to SPI the same treatment that was applied to I2C some times ago:
Make use of a generic implementation over spi1::RegisterBlock instead of generating several implementations with a big macro.

spi: use generic impl over spi1::RegisterBlock to avoid the need for macro

---

Cargo.toml
src/qei.rs
src/timer.rs

Updates the crate to use the latest stm32f4 release.
This fixes my build issues in #107
Builds fine with the stm32f411 feature (the controller I have access to).
Tested compile works with tools\check.py

Update stm32f4 dependency

---

CHANGELOG.md
src/timer.rs

When a TIM interrupt fires, it needs to be cleared, otherwise it will immediately retrigger. This patch adds a HAL method to do so, removing the need for unsafe low-level access.
Example:
```rust
/// This variable holds a reference to TIM2, which will be accessed in the ISR in order
/// to clear the interrupt flag.
static TIMER_TIM2: Mutex<RefCell<Option<Timer<stm32::TIM2>>>> = Mutex::new(RefCell::new(None));
fn main () -> ! {
// ... setup skipped ...
let mut timer = Timer::tim2(dp.TIM2, 1.khz(), clocks);
timer.listen(Event::TimeOut);
// Store the timer reference in the global variable
free(|cs| *TIMER_TIM2.borrow(cs).borrow_mut() = Some(timer));
}
#[interrupt]
fn TIM2() {
free(|cs| {
// Access the global timer reference and clear the timer interrupt
if let Some(ref mut tim2) = …
```

Add method for clearing TIMx interrupt flags

---

src/gpio.rs

According to RM0090 12.3.6, a "bit is cleared by programming it to 1".
I have compiled, but not tested this on stm32f4xx. However, I found this issue while porting the ExtiPin trait to stm32f1xx. I have tested this change on my stm32f1xx-hal working copy.
See also https://github.com/stm32-rs/stm32h7xx-hal/pull/41

Fix clear_interrupt_pending_bit()

---

.travis.yml
examples/ssd1306-image.rs
examples/stopwatch-with-ssd1306-and-interrupts.rs

Tested on an STM32F411 Nucleo dev board.
Solution found in #99 to get the examples to actually show something on the display. The Travis command to test the examples should obviously be folded into the Python check script - can someone help me do that? I have zero Python knowledge.
Closes #116 
Cc jamwaffles/ssd1306#100

Fix examples, test them in CI

---

CHANGELOG.md
src/gpio.rs
src/i2c.rs

This allows us to differentiate between a non open-drain and open-drain
alternate function configuration and require the open-drain variant for
I2C use to prevent hot smoke resulting from a misconfiguration.
Fixes #99

Added open drain Alternate modes and ways to construct them

---

.travis.yml
CHANGELOG.md
Cargo.toml
examples/usb_serial.rs
src/rcc.rs

Tested here, and ported my keyboard using this. Working as expected.
https://github.com/TeXitoi/keyberon-f4/commit/3375e744b7fb6cd476455a52bd423f4f08184d41
So, writing this with this code.
Some hand testing:
```
.use_hse(25_000.khz())
.sysclk(84.mhz())
.require_pll48clk() // same without this
Clocks {
hclk: Hertz(
84000000,
),
pclk1: Hertz(
42000000,
),
pclk2: Hertz(
84000000,
),
ppre1: 2,
ppre2: 1,
sysclk: Hertz(
84000000,
),
pll48clk: Some(
Hertz(
48000000,
),
),
}
.use_hse(25_000.khz())
.sysclk(83.mhz())
.require_pll48clk()
clocks = Clocks {
hclk: Hertz(
84000000,
),
pclk1: Hertz(
42000000,
),
pclk2: Hertz(
84000000,
),
ppre1: 2,
ppre2: 1,
sysclk: Hertz(
84000000,
),
pll48clk: Some(
Hertz(
48000000,
),
),
}
.use_hse(25_000.khz())
.sysclk(83.mhz())
//.require_pll48clk()
clocks = Clocks …
```

Require pll48clk

---

CHANGELOG.md
src/bb.rs
src/lib.rs

I started a PWM implementation for this HAL and since different channels share the same register we need to make sure that only a single channel modifies the register at a time if we want to split them. So I decided to make this PR to pave the way. Also It can be a solution to the problem of the non-atomically modifying of the `RCC` registers during peripheral initialization.
I would appreciate some opinions about this approach. 
CC @therealprof 
PS: Inspired by the implementation in the F1 HAL.

Implement bit-banding

---

CHANGELOG.md
Cargo.toml
examples/rng-display.rs
src/lib.rs
src/prelude.rs
src/rng.rs

Enables use of the RNG (random number generator) peripheral available on some stm32f4 chips. 
This PR includes an example openocd configuration for running the example.

Add Rng interface and an example that uses it.

---

CHANGELOG.md
src/rcc.rs

According to the manual:
>The clocks are divided with the new prescaler factor from 1 to 16 AHB cycles after write.
Switching the system clock before that can cause problems since some clock domains have maximum allowed values.

Wait for the new prescalers values to take effect

---

src/lib.rs

Tested USB device support for STM32411E device using STM32F411E Discovery board. Serial USB example works on STM32F411E (see https://github.com/ericevenchick/stm32-usbd-examples).

add otg_fs support for stm32f411

---

.github/workflows/ci.yml

Use build matrix instead of serialising builds

---

src/adc.rs

The External Trigger example currently uses an old stm32f4 API and doesn’t compile. This PR updates the example according to the latest API.

Update Code Example on adc.rs

---

CHANGELOG.md
Cargo.toml
examples/dwt-blinky.rs
src/dwt.rs
src/lib.rs

Implements "dwt cycle counter"-based `use embedded_hal::blocking::delay::{DelayMs, DelayUs};`
Additionally you can use it to measure execution times of code fragments.
Feel free to comment on which function names should change!
```rust
use crate::hal::{
dwt::{ClockDiff, DelayS, DwtExt, StopWatch},
prelude::*,
stm32,
};
// Constrain DWT and DCB
let dwt = cp.DWT.constrain(cp.DCB, clocks);
// Create a (copy-/cloneable) delay instance
let delay = dwt.delay();
// DelayMs/DelayUs from hal
delay.delay_us(1000);
delay.delay_ms(1);
// DelayS from dwt.rs
delay.delay_s(0.0000005f32);
delay.delay_s(0.0000005f64);
// Measure some closures timing
let t = dwt.measure(|| delay.delay_ms(10));
let _t: f64 = t.as_secs_f64();
let _t: f32 = t.as_secs_f32();
let _t: u64 = t.as_nanos();
let _t: u32 = …
```

Dwt: Delay and stopwatch

---

CHANGELOG.md
examples/sd.rs
src/sdio.rs

There are cases in which the bus cannot run at 24MHz, for example due to PCB layout issues.
This PR makes the bus frequency selection a part of the public API, allowing the user to run the SDIO bus at a lower frequency, if necessary.

Make SDIO bus frequency selectable

---

CHANGELOG.md

Somehow the sdio entry ended up in the released section. Correct the mistake.

Move sdio to unreleased section

---

CHANGELOG.md
src/i2c.rs

This allows us to reuse the code for both write_read() and write() where
we need to add a STOP condition after sending the data.

Move I2C write implementation into write_bytes function

---

src/lib.rs

Since the [synopsys drivers](https://github.com/stm32-rs/synopsys-usb-otg) now largely support the f446 (give or take a couple endpoints), I thought it'd be a good moment to send this PR to actually enable access to the relevant registers in this crate

Make USB peripherals accessible for the f446

---

src/i2c.rs

This peripheral is very similar to the one found in newer MCUs e.g.
STM32F0 and was taken from there.

Add implementation for Fastmode+ I2C available on select MCUs

---

CHANGELOG.md
src/gpio.rs

Since `InputPin` is implemented for pins in output mode, it also makes sense to implement `ExtiPin`. Especially useful in open drain mode.

Implement ExtiPin for pins in output mode

---

CHANGELOG.md
src/gpio.rs

This is needed to properly use pins where the interrupt vector is shared between multiple pins. Copied and pasted from stm32f1xx-hal, except that I changed the method to `&self` as opposed to `&mut self` because that makes more sense for a getter.
Personally I'd prefer a single method that both checks and clears the interrupt bit in one operation and returns if it was set, but I'm not sure if that has issues in some use cases. This way the user gets to decide.

Add check_interrupt method for GPIO pins

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/sdio.rs

Clean up the sdio driver by moving the parsing of the various sd response to a separate library https://crates.io/crates/sdio-host. Some other cleanups related to this change was made as well.

Move sdio response parsing to library

---

CHANGELOG.md
src/dac.rs
src/lib.rs
src/prelude.rs

Copied from stm32f0xx-hal
We should maybe wait until this shakes out?
https://github.com/stm32-rs/stm32f0xx-hal/pull/70/files

dac copied from stm32f0xx-hal

---

Cargo.toml
examples/qei.rs

I tested this on a ["black pill"](https://stm32-base.org/boards/STM32F411CEU6-WeAct-Black-Pill-V2.0) dev board. This example just lights up the LED based on the rotary encoder direction, though the code also calculates the difference in position as you rotate it, so you could run some other code based on that difference.
On a side note, what are peoples' setups for building/flashing/running these examples? My setup:
* MacOS
* [`STM32F411CEU6`-based board](https://stm32-base.org/boards/STM32F411CEU6-WeAct-Black-Pill-V2.0)
* `CP2102` USB-serial converter <-> `STM32F411`
* `TX` <-> `A10`
* `RX` <-> `A9`
* `3V3` <-> `3.3`
* `GND` <-> `GND`
* `stm32flash` CLI for flashing the firmware
* I have to hold the `BOOT0` button down and then press the `NRST` button to put it in flashing mode
* …

Add a qei example

---

src/dma.rs
src/lib.rs
src/prelude.rs

Very minimal implementation of DMA. Splits DMA1 or DMA2 into their 8 streams, which give access to the stream's registers and interrupt bits.
Can be extended later, but this should be a good start.

Add DmaExt::split() and minimal dma::Stream.

---

CHANGELOG.md
examples/sd.rs
src/sdio.rs

Did a quick read of the Reference manual, and the ST hal driver looking for potential timing issues. Noticed that their driver have a delay, to make sure the time between disabling and enabling the clock is long enough. So I implemented that and moved the card power functionality to its own function.
The sdio registers are sensitive to consecutive writes (If I understand the Reference manual correctly) in relation to both SDIOCLK and PCLK2,  and shouldn't be written to repeatable within certain number of cycles. But as far as I can tell now we should be ok without adding additional delays in block read/write.
Made this a draft as I'm not sure my approach to using the clocks struct to create a 2 ms delay is correct.

Move power handling to its own function and add short delay to register update

---

CHANGELOG.md
Cargo.toml
src/sdio.rs

This updates the driver to use the latest sdio-host release and has some refactoring of the datapath code. It also fixes some stability issues with sd card writes that I was seeing.
With this patch my [usb mass storage example](https://github.com/jkristell/feather-f405/blob/master/examples/sd-usb-mass-storage.rs) works reliable.
So this is a pretty important patch for the sdio driver.

Cleanups and bugfixes for the sdio driver

---

src/dma/traits.rs
src/serial.rs

Based upon and dependent upon https://github.com/stm32-rs/stm32f4xx-hal/pull/186

 Allow DMA on both halves of a split Serial<USART> separately.

---

CHANGELOG.md
src/rcc.rs

for MCUs that support overclocking to 180 MHz.  The reference manual
states that this can be done while waiting for PLL lock.
Fixes #196

Enable the voltage regulator overdrive

---

src/serial.rs

In ref to #198
This is a copy of the hint for the Timer.

serial: remind users to NVIC::unmask interrupts

---

CHANGELOG.md
src/i2c.rs

This PR fixes #202 by adding the following:
1. During all busy-wait I2C loops, error flags are continually checked.
2. All fault flags have been updated to manually clear the fault indication.
cc: @therealprof

Adding NACK detection and fault condition clearing

---

CHANGELOG.md
src/serial.rs

This allows to send formatted output directly to the serial port instead
of having to split it as found in #214.

Add fmt::Write impl for Serial<USART, PINS>

---

CHANGELOG.md
src/adc.rs

This PR fixes #205 by updating the adc module to not allow access to VREF, VBAT, and the internal temperature sensor from ADC2 and ADC3, since these are only available to ADC1. To accomodate the loss of external reference calibration, the adc configuration has been updated to allow the user to specify the VDDA voltage.

Updating ADC to support external reference specifications

---

src/serial.rs

I think the baudrate calculation before was... ~~really wrong~~ slightly misunderstood.
As far as I can tell, this new method is correct according to the stm32F411 datasheet, I'm not sure if the calculation is consistent across all stm32f4xx devices.
This was validated with an stm32f411, a pclk2 of 96MHz, and a baudrate of 12mbps.

Correct Serial Baudrate calculation

---

CHANGELOG.md
src/timer.rs

@thalesfragoso suggested this fix in matrix.
rtic init:
```rust
let mut timer = Timer::tim5(ctx.device.TIM5, 10.hz(), clocks);
timer.listen(Event::TimeOut);
pb5.set_high().ok();
```
rtic isr:
```rust
#[task(binds = TIM5, resources = [led, sm, pb5])]
fn timer5_isr(ctx: timer5_isr::Context) {
let tim = unsafe { &(*stm32::TIM5::ptr()) };
ctx.resources.pb5.toggle().ok();
tim.sr.modify(|_, w| w.uif().clear_bit());
}
```
PB5 pin trace, notice the glitch:
With this fix timings are perfect:

timer: trigger update event to load the registers

---

CHANGELOG.md
examples/analog-stopwatch-with-spi-ssd1306.rs
examples/stopwatch-with-ssd1306-and-interrupts.rs
src/gpio.rs
src/lib.rs
src/prelude.rs
src/syscfg.rs

This should prevent terrible user experience when SYSCFG is used without its clock enabled.
Note that this is a breaking change.

Add syscfg driver to enforce clock enable 

---

CHANGELOG.md
Cargo.toml
src/dma/mod.rs
src/dma/traits.rs

The initial idea of the DMASet trait was that people could __unsafely__ implement it themselves from outside of the HAL. Unfortunately, we missed the problem with the fact that tuples are considered a foreign type. This PR drops the tuple approach but still maintains the check that DMASet provides.
I also added a fix for #227.
Fixes #227 
This is also a possible solution to #226, but it takes a different approach, it still forces people (or the HAL) to make a new type if they want a "non-default" memory size (or address). This is more verbose than just dropping the associated type of `PeriAddress` in favor of a generic parameter, but, IMO, the verbosity can be an advantage here.
Marking as a draft because I still want to make sure this works as intended and that there isn't another corner …

DMA: Fix problems with DMASet and timer wrappers

---

CHANGELOG.md
src/timer.rs

This is a straight-up copy of the `MonoTimer` from the `stm32f1xx-hal` crate:
https://github.com/stm32-rs/stm32f1xx-hal/blob/d976ba2312fae2f1b15707573bc5d82ea00ba73f/src/time.rs#L229-L278
I wanted the same functionality in a stm32f4-based project. I tested it on an `stm32f411CE` [WeAct USB C board](https://stm32-base.org/boards/STM32F401CEU6-WeAct-Black-Pill-V3.0), and it seems to behave properly.

Port MonoTimer from stm32f1xx-hal

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
examples/can-send.rs
src/can.rs
src/lib.rs

This adds support for can with the bxcan crate. This differs slightly from the stm32f1 pull request and the stm32f7 pull request: the `Can::new` method takes ownership of the pins, which requires the user to configure the pins correctly, and doesn't use the afio functionality, which doesn't appear to be present here.

add can support

---

CHANGELOG.md
src/rcc/mod.rs

Also add a missing entry for it to the changelog.
This isn't really breaking because this isn't released yet.

Make freeze_unchecked method private

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/rcc/mod.rs
src/rtc.rs

This PR adds RTC support for the stm32f4 series SoCs. This is based on the stm32f3 code by @David-OConnor, and ST reference examples. Set and get of time, and individual hour/minute/second/day/month/year all tested successfully. Have not tested full date set, but uses the same code and should work fine.
Personally tested on a ST Nucleo F446RE board. Very similar to https://github.com/stm32-rs/stm32f7xx-hal/pull/96
Has CHANGELOG entry.
Not sure if this will auto-populate reviewers, but will call out @therealprof as I've seen that name on quite a few sign-offs. :)
Please let me know if anything needs to be modified.
Thanks,
-Matt

Add rtc support

---

CHANGELOG.md
src/rcc/pll.rs

While testing I2S on an STM32F412, I found that the clock setup code was not correctly configuring the I2S PLL. The clock setup code found a good configuration, but did not write it correctly to the PLL configuration register. The PLLI2SCFGR.PLLI2SN field was left at its default value.
This pull request changes one function to write PLLI2SCFGR.PLLI2SN when applying a PLL configuration.
The updated code is working well for I2S on my STM32F412. I don't have an F413, F423, or F446 to test with, but this seems like a simple fix that is unlikely to break other code.

RCC for F412, F413, F423, F446: Add missing configuration of PLLI2SCFGR.PLLI2SN

---

CHANGELOG.md
src/can.rs
src/lib.rs

I looked through all the STM32F4 datasheets to find additional pins that can be used for CAN, and added implementations of the `can::Pins` trait for those pins. As part of the process, I enabled the `can` module for several STM32F4 models that support CAN beyond the F405, F407, and F446. I also added CAN3 and the associated pins for F413 and F423 models.
This also includes some small documentation improvements that I thought might be helpful.
I'm not sure if this needs a changelog entry because it's in the same version where CAN support was first added. I added one anyway to make the automated checks happy.

CAN: Add more pins, support CAN for more models, add CAN3 where available

---

CHANGELOG.md
src/rcc/mod.rs

This change adds an option to set the HSEBYP bit of RCC_CR, which disables the built-in oscillator for the HSE clock. Instead, the microcontroller can use a clock signal from an external oscillator or other source.
I have tested this mode on a 32F412GDISCOVERY board.

RCC: Add option to bypass HSE oscillator

---

CHANGELOG.md
src/spi.rs

I'm already aware of #223 but I tried it and...  It doesn't work.  I sort of went back to the drawing board on it and created my own PR that I've tested so I know it works 👍
If errors are encountered during an SPI write it'll automatically clear any bits that need clearing *then* return the error.  So you get the bit cleared and the error.  What more could you ask for? :smile:

Clear SPI errors on send to prevent races

---

CHANGELOG.md
src/serial.rs

This PR modifies the serial module to use generics instead of macros, so that downstream libraries can take advantage of generics. It also includes compatibility functions so that existing code continues to work without modifications.
Feedback is appreciated. The implementation here is ugly, IMO, but the advantage to users of the library is clear.

change Serial to use generics instead of macros

---

CHANGELOG.md
src/rcc/pll.rs

I was testing I2S and noticed that the actual sample rate was wrong (on an STM32F411 this time). I noticed that while the STM32F411 has a separate M divider before the I2S PLL, the clock setup code was not configuring it in the PLLI2SCFGR.
This pull request proposes to change two of the #[cfg] attributes so that the code sets PLLI2SCFGR.PLLI2SM on the STM32F411, like it already does on the F412/413/423/446.
The changed code works and generates the correct sample rate on my STM32F411.

RCC for F411: Add missing configuration of PLLI2SCFGR.PLLI2SM

---

CHANGELOG.md
src/i2c.rs

As outlined in #274, the I2C module may indicate spurious bus errors. This PR removes the `Error::BUS` variant from the I2C interface and updates the status flags check to ignore BERR bit assertions.
This fixes #274 
TODO:

Errata workaround: Removing error return on I2C bus error detection

---

CHANGELOG.md
src/sdio.rs

As per page 46 of https://www.st.com/resource/en/datasheet/stm32f411ce.pdf, the `SDIO_D0` pin option is actually on PB7, not `PB6`.
The `PB6` assignment appears to be correct for the other three microcontrollers.

Update SDIO_D0 pin to PB7 for stm32f411

---

CHANGELOG.md
src/crc32.rs

The current implementation of the CRC32 perhipheral does not enable the CRC32 clock.
On the STM32F446﻿, this causes **all** calculations against this peripheral to emit an incorrect null instead of the checksum.
This PR enables the CRC clock when the HAL's peripheral is acquired, and disables it when released.
Fixes #281

Fix CRC32 peripheral

---

CHANGELOG.md
Cargo.toml

This PR is to switch the version requirement for` bxcan` to  ">=0.4, <0.6". See #285 for more details.

Test bxcan version relax

---

CHANGELOG.md
src/sdio.rs

With this crates update of the PAC dependency came my PAC patches to the sdio peripheral. This PR adjust the sdio driver to take advantage of those changes.
This should get rid of the warnings about unnecessary unsafes in the sdio driver.

Updates and cleanups to match the changes in the PAC

---

CHANGELOG.md
Cargo.toml
examples/rtic.rs

This example presents integration with RTIC [1]. Built for STM32F4
Discovery, toggles an onboard LED upon an interrupt fired by an onboard
button.
[1] https://rtic.rs/
Signed-off-by: Petr Horacek <hrck@protonmail.com>

Add an RTIC example

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
examples/cs43l22/mod.rs
examples/i2s-audio-out-dma.rs
examples/i2s-audio-out.rs
src/i2s.rs
src/lib.rs
tools/check.py

Welcome to my first large pull request, which adds support for I2S audio communication using supported SPI peripherals. Like the way we support CAN with the bxcan library, I am proposing to support I2S using my [stm32_i2s_v12x](https://crates.io/crates/stm32_i2s_v12x) library.
Although stm32_i2s_v12x is in a separate repository, we can also talk about it here.
* The I2S module is available if the `i2s` feature is enabled, in order to not increase compile time for applications that don't use I2S.
* All four modes are supported: master transmit, master receive, slave transmit, and slave receive.
* Basic support for DMA, interrupts, and error detection is provided.
* All STM32F4 models are supported.
* I added two examples that run on the STM32F411E-DISCO board and send audio to the on-board …

Add I2S communication using SPI peripherals

---

CHANGELOG.md
src/gpio.rs

This PR adds the ability to configure the internal pullup resistor for `AlternateOD` pin types, for example if you want to use i2c with internal pullup resistors etc.
Tested on STM32F411RET6U

Add internal pullup setting for AF open drain

---

CHANGELOG.md

With three recently merged pull requests, we ended up with two "Added" sections in different parts of the unreleased section of the changelog. I propose to combine them into one section, above the "Changed" section.

Fix duplicate "Added" sections in changelog

---

CHANGELOG.md
Cargo.toml
examples/serial-9bit.rs
src/serial.rs

In [issue 280](https://github.com/stm32-rs/stm32f4xx-hal/issues/280), Maldus512 asked how to use 9-bit words with the serial driver. I noticed that the current code did not allow that use, so I decided to improve the code.
I added a `WORD` type parameter to `Serial`, `Tx`, and `Rx`. It defaults to `u8`, so that existing code will not break. I also added functions to convert between `Serial<USART, PINS, u8>` and `Serial<USART, PINS, u16>`.
I added some trait implementations that use `u16` as the word type instead of `u8`:
* `impl<USART> serial::Read<u16> for Rx<USART, u16>`
* `impl<USART> serial::Write<u16> for Tx<USART, u16>`
* `impl<USART> blocking::serial::Write<u16> for Tx<USART, u16>`
* `impl<USART, PINS> serial::Read<u16> for Serial<USART, PINS, u16>`
* `impl<USART, PINS> …

USART: support reading and writing 9-bit words, change to 32-bit data register access

---

CHANGELOG.md
Cargo.toml
examples/adc_dma_rtic.rs
src/adc.rs
src/dma/traits.rs

Implements the PeriAddress trait for Adc, making it possible for it to be used with the Transfer DMA implementation.
Fixes a rounding problem in the temperature equation. 
Fixes temperature sensor channel assignment for F405. The problem seems to affect all of the F40x and the F41x as the reference manual claims that the channel is 16 instead of 18.

Add support for DMA with the ADC wrapper.

---

CHANGELOG.md
src/dma/mod.rs

fixed typo in string representation of DMAError type

simpe typo fix in dma error type

---

CHANGELOG.md
examples/adc_dma_rtic.rs
examples/i2s-audio-out-dma.rs
src/dma/mod.rs

Memory to peripheral transfers now only require read access to the buffer
I tried to reduce code duplication, but some of it is necessary. This removes a big constrain on memory-to-peripheral transfers.
Draft because I need to look at some stuff and do some testing.

DMA: Support both WriteBuffer and ReadBuffer

---

CHANGELOG.md
src/fsmc_lcd/pins.rs

I noticed that some of the pin definitions for the FSMC LCD interface that I added in [pull request 297](https://github.com/stm32-rs/stm32f4xx-hal/pull/297) were wrong. A few of the pins use AF10 when I had assumed that they all use AF12, and pin PD2 should have been included. Here's a fix.

Fix pin definitions for FSMC LCD interface

---

CHANGELOG.md
src/timer.rs

ATX-compatible fans have PWM speed control inputs that they internally pull up (to 5.2.5 V maximum). To correctly control the speed of these fans, a microcontroller needs to generate a PWM signal with a pin in open-drain mode.
This pull request makes the PWM code support `AlternateOD` mode in addition to `Alternate` mode for all currently supported pins.

Add open-drain pin mode support for PWM output

---

CHANGELOG.md
src/dma/mod.rs
src/dma/traits.rs

This PR adds the missing methods to retrieve the error flags for dma streams.

adds missing dma error flags

---

CHANGELOG.md
examples/analog-stopwatch-with-spi-ssd1306.rs
examples/blinky-timer-irq.rs
examples/delay-blinky.rs
examples/dwt-blinky.rs
examples/f413disco_lcd_ferris.rs
examples/i2s-audio-out-dma.rs
examples/i2s-audio-out.rs
examples/qei.rs
examples/rtic.rs
examples/serial-9bit.rs
examples/ssd1306-image.rs
examples/st7789-lcd.rs
src/gpio.rs
src/prelude.rs

Gpio inherent

---

CHANGELOG.md
examples/i2s-audio-out-dma.rs
src/gpio.rs

Added compatibility constants to keep `Alternate<AFx>` working just as before

---

CHANGELOG.md
src/i2c.rs
src/serial.rs
src/spi.rs

Use unrepeatable macros. Work better with rustfmt

Spi::new + macro cleanups

---

CHANGELOG.md
Cargo.toml
examples/pwm-input.rs
src/lib.rs
src/pwm_input.rs

It also presently depends on side effects﻿, due to my limited experience writing at the HAL layer.
There is also one unsafe block when configuring the prescalers, as it seems (or my IDE is failing me) that the prescaler's don't have safe abstractions for configuring them.
Thnkgs that need be done:
Feedback and suggestions are welcome.

PWM Input abstraction

---

CHANGELOG.md
src/gpio.rs
src/i2c.rs
src/i2s.rs
src/serial.rs
src/spi.rs

One `NoPin` type and `NoTx`, `NoSck etc. are aliases for it.
Use `(TX, RX)` directly in constructors instead of `Pins`. Better for docs:
vs

NoPin & no Pins

---

CHANGELOG.md
src/flash.rs
src/gpio/convert.rs
src/lib.rs

Instead of #239 
Rebased. 
```rust
Iterator<Item = &'a u8>
```

Implement flash read/erase/program

---

CHANGELOG.md
src/serial.rs

This PR adds `listen` and `unlisten` functions for the RX and TX only USART modes.
It also adds functions for checking the relevant interrupt flags and for clearing the idle line interrupt flag.

Add listen/unlisten for RX/TX-only USART

---

CHANGELOG.md
src/fmpi2c.rs
src/gpio.rs
src/gpio/convert.rs
src/i2c.rs
src/i2s.rs
src/serial.rs
src/spi.rs

With this PR passing `into_alternate()` is not necessary (but still can be used) when you work with `Serial`, `Spi`, `I2c` or `I2s`.
Pins will be internally switched in alternated mode and restored on `release`.

SetAlternate

---

CHANGELOG.md
src/timer.rs

Adds support for PWM outputs to timers 9-14 as mentioned in issue #361.  I think I got all the channels that are supported by the HAL (that is, channels 1-4 non-inverted; inverted pins, ETR, and BKIN are not covered).  A spreadsheet detailing the pins has been uploaded to the issue.
Eliminates the "tim8" configuration feature block in favor of keeping all feature gates based on the part number.  This lets the block that formerly contained TIM8 channels also contain channels for TIM10-14.
Uncomments two pins for TIM5 that are on the datasheet, and I don't see an errata suggesting they shouldn't be used.

Add PWM channels for timers 9-14

---

CHANGELOG.md
Cargo.toml
examples/spi_dma.rs
src/dma/traits.rs
src/spi.rs

This is a first draft of what DMA support for SPI would look like.
I don't have a great opinion on how some of the error flags can/should be used in conjunction with DMA transfers and would love some advice.
Once #318 has been merged, I'll update the example to look at the extra error flags to show multiple transfers.

adds dma support for spi

---

CHANGELOG.md
examples/rtic-tick.rs

The rtic-tick example asserts during clock setup because the code attempts to configure a clock of 8 MHz, which is below the lowest `SYSCLK_MIN` defined in `src/rcc/mod.rs` (12.5 MHz).  Change requested clock to 48 MHz (above the highest `SYSCLK_MIN` of 24 MHz).

Change rtic-tick example system clock to fix assert.

---

CHANGELOG.md
src/sdio.rs

When testing with an eMMC module driven at frequencies above 12MHz, I found that `write_block` would consistently fail with either `Crc`, `DataCrcFail`, or `Timeout` errors.
Here's a sample probe output collected on the CLK and D0 lines at 24MHz. D0 has a relatively clean data block and corresponding CRC, but the very end of the transmission spends a clock cycle at ~1V (when powered by 3V3) and has large rippling peaks at nearby level transitions.
As it turns out, the code in `write_block` is polling the eMMC (or SD card) status even while still transmitting on the data lines. Preventing the status commands from being sent until the transmission is complete (TXACT low) prevents the interference and allows writes to consistently succeed at any speed/bus width. It's unclear why the …

Wait for SDIO transmission to finish before polling card status

---

CHANGELOG.md
src/adc.rs

since the discussion in #362 seems to come to a conclusion, and my personal measurements supported that, I think it's time to actually fix it.
This will change max_sample from 1<<n-1 to 1<<n,
After this PR ADC readings will change, but will be more accurate than before. Users might be confused since they won't get a reading of 3300mV, but this is correct behaviour.

fix #362: ADC voltage conversion might be incorrect

---

CHANGELOG.md
src/sdio.rs

Rewrite the loop conditionals to silence clippy.
Tested on a feather-f405 board.

Fix clippy warnings

---

CHANGELOG.md
src/gpio.rs

PR #266 has added a `internal_pull_up()` function. This PR adds `internal_pull_down()` for symmetry reasons

Add internal_pull_down() method

---

CHANGELOG.md
Cargo.toml
examples/adc_dma_rtic.rs
examples/analog-stopwatch-with-spi-ssd1306.rs
examples/blinky-timer-irq.rs
examples/rtic-tick.rs
examples/stopwatch-with-ssd1306-and-interrupts.rs
examples/timer-periph.rs
examples/timer-syst.rs
src/prelude.rs
src/timer.rs
src/timer/counter.rs

~~Not for SysTick for now~~ Use 1 microsecond as minimal timeout for SysTick `Counter`
This PR lets to use `fugit` units for timer including values bigger then 1 second.
Sampling of timer (time of 1 tick) now can be set in by FREQ generic constant.

try to use fugit::Duraction for CountDown::Time

---

CHANGELOG.md
examples/adc_dma_rtic.rs
src/adc.rs
src/dma/mod.rs
src/dma/traits.rs

This PR should fix adc with dma issues as mentioned in #282: "DMA Transfer consumes peripheral".
Changes:
- DMA Transfer exposes a reference to the peripheral, currently only for PeripheralToMemory
- the ADC provides a closure similar to sample_to_millivolts
- a demonstration of its use in the adc_dma_rtic example.
As of now this PR is not complete; I kindly ask to review the concept before I complete the implementation, documentation and squashing.

adc improvements for dma

---

CHANGELOG.md
src/rcc/pll.rs

Setting the common target PLL freq of 49.152 MHz for the SAI clock (192kHz * 256) results in an overflow during multiplication. This patch catches the overflow, though I'm sure there's a better approach to optimizing the PLL settings that could avoid this.

Prevent overflows optimizing SAI PLL

---

CHANGELOG.md
src/gpio/alt.rs

Reference [stm32f446 datasheet](https://www.st.com/resource/en/datasheet/stm32f446re.pdf) pages 55 and 58.

Add missing CAN1 pin mapping for stm32f446

---

CHANGELOG.md
Cargo.toml
src/flash.rs

This PR implements [embedded-storage](https://github.com/rust-embedded-community/embedded-storage) traits for flash.
One major headache with F4 series is dual-bank flash and non-uniform sector sizes, which required quite a bit of code to abstract away. I went through all of the F4 reference manuals and believe that `flash_sectors(...)` function should be correct for all variants. AFAIK, there is no single source about flash layout for all the chips. Moreover, ST [lists](https://www.st.com/en/microcontrollers-microprocessors/stm32f4-series.html#products) F429 and F469 with 512 KB of flash as dual-bank, but there is no information about it in the reference manual. I believe this could be an error in the website and only 1 MB chips have dual-bank capabilities.
The PAC crate is also missing …

Implement embedded-storage traits

---

CHANGELOG.md
Cargo.toml
examples/sd.rs
src/sdio.rs

Followup to https://github.com/jkristell/sdio-host/pull/10, which will also be required before this PR can be merged (cc @jkristell)
This PR adds support for eMMC peripherals using the SDIO module. `Sdio` is now generic over an `SdioPeripheral`, which can either be a `SdCard` or `Emmc`. Many of the methods are generic enough to be shared between both, although some (like initialization) need to be specialized for each.

Support eMMC in SDIO module

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Right now on relase 0.12 (and master) this:
```
DEFMT_LOG=debug cargo build --release --features=rt,stm32f405,defmt --examples
```
fails to compile due to `defmt` support in fugit not being enabled.
This workaround fixes that, but feels like a hack.
It's described here: https://blog.turbo.fish/cargo-features/
The other option is to rename the fugit feature under a different name, but this fix could be used until then.
Let me know if you want this to be merged and I can write a Changelog entry.

Fix defmt support

---

CHANGELOG.md
src/rcc/mod.rs

Fix `rcc` example.

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Remove the defmt feature/crate naming workaround

---

CHANGELOG.md
Cargo.toml
examples/spi_slave_dma_rtic.rs
src/spi.rs

as mentionned in issue https://github.com/stm32-rs/stm32f4xx-hal/issues/483

adding spi slave

---

CHANGELOG.md
src/gpio.rs
src/gpio/partially_erased.rs

I implemented the `For` trait for the following pin type conversions:
- From `Pin<P, N, MODE>` to `PartiallyErasedPin<P, MODE>`
- From `Pin<P, N, MODE>` to `ErasedPin<MODE>`
- From `PartiallyErasedPin<P, MODE>` to `ErasedPin<MODE>`

From trait for Pin, PartiallyErasedPin, and ErasedPin structs

---

CHANGELOG.md
src/serial.rs
src/serial/hal_02.rs
src/serial/hal_1.rs

Related to #505 
Instead of changing API I added alternative.
So now to can choose between `Tx`, `Rx` with erased information about pins and `UTx`, `URx` which can join to restore `Serial`

Serial Tx, Rx containing pins

---

CHANGELOG.md
src/bb.rs

The generated code for the functions is usually only 1-2 instruction(s),
calling such a function causes more overhead than inlining it. Most
example binaries shrink up to 1kB by this hint.

Apply #[inline] attribute to bitbanding functions.

---

CHANGELOG.md
src/spi.rs
src/spi/hal_02.rs
src/spi/hal_1.rs

Spi u16 frame

---

CHANGELOG.md
src/adc.rs

For each MCU listed checked ST's reference manual for temperature sensor ADC input pin.
Some are exclusively `ADC1_18`, others have `ADC1_16` available, and some are shared. Opted to use `ADC1_16` when available, always giving preference to what the manual says to use in order to read temperature.
Example:
[STM32F411 Reference Manual page 226](https://www.st.com/resource/en/reference_manual/dm00119316-stm32f411xc-e-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf)

Revised ADC temperature sensor pins

---

CHANGELOG.md
Cargo.toml

Fixes an issue with FIFO allocation limits. tl;dr the previous version assumed that 16 32-bit words were allocated for every _possible_ TX endpoint, when only active endpoints should be considered.
See stm32-rs/synopsys-usb-otg#26

Bump synopsys-usb-otg to 0.3.1

---

CHANGELOG.md
src/serial/hal_02.rs

Fix #528 .
Restore implementation accidentally removed in #514

fix removed Tx::Write<u8>

---

CHANGELOG.md
src/i2c.rs
src/i2c/hal_1.rs

A transactional HAL API implementation for I2C. Closes #445.
I have to rework i2c code to implement this:
* `prepare_read`, `prepare_write` - methods to send start and address only
* `write_wo_prepare`, `read_wo_prepare` - methods  like old `read`, `write` but they do not send start and address.
* `read_bytes`, `write_bytes` - this methods now only for send/receive. The do not send start, stop or address.
* All public api's behaviour is untouched so there are no breaking changes for users.
Note: I have to create duplicate methods `transaction_slice` and `transaction` because `Operation` doesn't implement Clone to send slice as iterator.

Transactional I2C

---

CHANGELOG.md
Cargo.toml
examples/display_touch.rs

Added example to use the ft6x06 touchpanel controller. This example works on STM32F412-G and STM32F413-H discovery boards. It configures the i2c bus and uses ft6x06 crate to get touch coordinates data.

Touchscreen driver

---

CHANGELOG.md
src/timer.rs
src/timer/pwm.rs

When changing the period of a PWM timer repeatedly, it will sporadically stop working. This is because the CNT register isn't being reset.
Minimum reproducible example:
```rust
#![no_main]
#![no_std]
// use panic_halt as _;
use panic_semihosting as _;
use cortex_m_rt::entry;
use stm32f4xx_hal as hal;
use crate::hal::{pac, prelude::*, timer::Channel};
#[entry]
fn main() -> ! {
let dp = pac::Peripherals::take().unwrap();
let buzzer = dp.GPIOA.split().pa0.into_alternate();
// Set up the system clock. We want to run at 48MHz for this one.
let rcc = dp.RCC.constrain();
let clocks = rcc.cfgr.use_hse(25.MHz()).sysclk(48.MHz()).freeze();
let mut pwm = dp.TIM5.pwm_hz(buzzer, 1000.Hz(), &clocks);
pwm.set_duty(Channel::C1, pwm.get_max_duty() / 2);
pwm.enable(Channel::C1);
let mut delay = …
```

Reset timer CNT register when PWM period is changed

---

CHANGELOG.md
src/gpio.rs
src/gpio/outport.rs
src/gpio/partially_erased.rs
src/prelude.rs

~~This is draft of [`OutputPort<u8>`](https://github.com/rust-embedded/embedded-hal/pull/134)~~

OutputPort

---

examples/delay-syst-blinky.rs

as the on & off periods are the same and it doesn't matter what the initial state is we can just use `toggle` instead of `set_high` and `set_low`.
the latter is still present in other examples, e.g. `delay-timer-blinky` which uses different delays for the on & off periods.

`delay-syst-blinky` example: us `toggle`

---

CHANGELOG.md
src/sdio.rs

Using SDIO above 12 MHz causes clock glitches, which result in CRC errors (at least in embassy-stm32). In this HAL, the CRC error is not caught and write silently fails without changing any bytes on SD card.
Section from `STM32F42xx and STM32F43xx Errata sheet`:
```
2.13.1 SDIO HW flow control
Description
When enabling the HW flow control by setting bit 14 of the SDIO_CLKCR register to ‘1’,
glitches can occur on the SDIOCLK output clock resulting in wrong data to be written into
the SD/MMC card or into the SDIO device. As a consequence, a CRC error will be reported
to the SD/SDIO MMC host interface (DCRCFAIL bit set to ‘1’ in SDIO_STA register).
Workaround
None.
Note: Do not use the HW flow control. Overrun errors (Rx mode) and FIFO underrun (Tx mode)
should be managed by the application …
```

Fix SDIO hardware flow control errata

---

CHANGELOG.md
examples/rtic-adc-dma.rs

@apollolabsdev asked on Discord what was going on in the adc_dma_rtic example, and I explained it as best I could.
They seem to understand it enough to write a blog post about it, so I assume my help was sufficient.
This is the gist of that.

Comment buffer usage in adc_dma_rtic example

---

CHANGELOG.md
src/spi.rs

Add `SPI::new*` and `SpiExt::spi*` docs.
See [#564](https://github.com/stm32-rs/stm32f4xx-hal/issues/564) for details.

Improve SPI::new* docs

---

CHANGELOG.md
src/dma/traits.rs

DMA traits for the HAL serial type were missing for some of the U(S)ARTs. The trait was only implemented for the PAC in some places.
The users can now for example use.
```
let dma1 = StreamsTuple::new(cx.device.DMA1);
let uart_dma_cfg = DmaConfig::default().transfer_complete_interrupt(true).memory_increment(true);
let (tx, rx) = Serial::new(
cx.device.UART4,
(tx_pin, rx_pin),
serial::Config::default()
.baudrate(9600.bps())
.wordlength_8()
.parity_none()
.stopbits(serial::config::StopBits::STOP1)
.dma(serial::config::DmaConfig::Rx),
&clocks,
)
.unwrap()
.split();
let mut dma_rx_transfer = Transfer::init_peripheral_to_memory(
dma1.2,
rx,
cx.local.rx_buf0,
None,
uart_dma_cfg,
);
```
Without the pull request, the users would get `DMASet<..>` not implemented error for some the U(S)ARTs.

Added U(S)ART DMA traits for HAL serial types

---

CHANGELOG.md
Cargo.toml
examples/rtic-i2s-audio-in-out.rs
src/i2s.rs

I, we released an new version of stm32_i2s_V12x (now v0.4). This new version implement fix that require some API change

adapt to use stm32_i2s v4

---

CHANGELOG.md
Cargo.toml
examples/rtic-serial-dma-rx-idle.rs
src/dma/mod.rs

* Impl `Transfer.is_idle()` and `Transfer.is_rx_not_empty()` for `serial::Rx` and `uart::Rx`.
* Relax trait bounds this methods.
See #586 for details.

Allow dma::Transfer.peripheral() for serial::Rx

---

CHANGELOG.md

the version number was wrong (which also led to tools like dependabot not listing any changelog) and some links were missing.

fix changelong entry for release v0.16.0

---

CHANGELOG.md
src/prelude.rs
src/serial.rs
src/serial/hal_02.rs
src/serial/hal_1.rs
src/serial/uart_impls.rs
src/uart.rs

cc #630
@burrbull 
```rust
#[cfg(feature = "uart4")]
pub(crate) use crate::pac::uart4::RegisterBlock as RegisterBlockUart;
pub(crate) use crate::pac::usart1::RegisterBlock as RegisterBlockUsart;
pub trait RegisterBlockImpl {
fn new<UART: Instance<RegisterBlock = Self>, WORD>(
uart: UART,
pins: (impl Into<UART::Tx<PushPull>>, impl Into<UART::Rx<PushPull>>),
config: impl Into<config::Config>,
clocks: &Clocks,
) -> Result<Serial<UART, WORD>, config::InvalidConfig>;
fn read_u16(&self) -> nb::Result<u16, Error>;
fn write_u16(&self, word: u16) -> nb::Result<(), Error>;
fn read_u8(&self) -> nb::Result<u8, Error> {
// Delegate to u16 version, then truncate to 8 bits
self.read_u16().map(|word16| word16 as u8)
}
fn write_u8(&self, word: u8) -> nb::Result<(), Error> {
// Delegate to u16 version …
```

Join Serial for USART and UART again. Make inner traits with different implementation for USART and UART.

---

README.md

Corrected the link to config.toml in the "Setting up your project" section of README.md

Fixed broken config.toml link in readme

---

CHANGELOG.md
Cargo.toml
examples/rtic-dual-i2s-audio-in-out.rs
examples/rtic-i2s-audio-in-out.rs
src/gpio/alt.rs
src/i2s.rs

Hi, i'm trying to implement the 'device' that is suitable for full duplex i2s communication. I'd like to have opinion about implementation, i'm not sure it follow the general style of the crate. I don't have example to follow, I'm in a unusual situation where the 'device' is composed by 2 peripherals.

Dual i2s core

---

CHANGELOG.md
Cargo.toml
examples/qspi-w25q.rs
src/gpio/alt.rs
src/lib.rs
src/qspi.rs
src/rcc/enable.rs

This module implements the QuadSPI interface which allows high speed communication with external flash memory.
Limitations:
- Interrupts are not supported.
- Status polling mode is not supported.

Add a basic blocking QSPI interface

---

src/rcc/mod.rs

This just fixes a minor documentation typo I encountered - feel free to ignore if not required.

src/rcc: fix minor documentation typo

---

CHANGELOG.md
Cargo.toml
src/dwt.rs
src/fmpi2c/hal_1.rs
src/gpio/dynamic.rs
src/gpio/hal_1.rs
src/i2c.rs
src/i2c/hal_1.rs
src/serial/hal_1.rs
src/spi/hal_1.rs
src/timer/hal_1.rs

there were various breaking changes in alpha.9 and alpha.10 which have been applied here. see [their changelog][embedded-hal-1.0.0-alpha.10] for further details.
important: this is completely untested beyond "it compiles", please test this carefully!
compilation has been tested with the `stm32f401` feature, the CI will show whether it'll also compile for all others.
note that this does only the bare minimum to make it build against the new version - it does not implement any of the newly added APIs. this can be done in subsequent commits.
this fixes #602
[embedded-hal-1.0.0-alpha.10]: https://github.com/rust-embedded/embedded-hal/blob/v1.0.0-alpha.10/embedded-hal/CHANGELOG.md

update to `embedded-hal=1.0.0-alpha.10`

---

CHANGELOG.md
examples/rtic-serial-dma-rx-idle.rs
examples/rtic-spi-slave-dma.rs
examples/spi-dma.rs
src/dma/mod.rs
src/dma/traits.rs
src/i2c/dma.rs

Hi, i'm trying to rewrite the stream struct API, here is the list modification i'm doing on stream:
- implement missing feature (already discussed in another Draft Pull Request)
- remove unecessary generics (lready discussed elsewhere)
- replace "class" method by "object" method to follow "peripheral ownership pattern"
- remove "get" prefix on getter to follow coding style of rust compiler
- rename things, to give a more natural, shorter or less ambiguous name
- replace some raw parameter by enum to make thing safer or more natural
- disable method just write 0 to the enable bit. In my opinion, trying to handle thing when disabling  the hardware is the 
- role of an higher level abstraction
This is what i'm doing on Transfer struct
-adapt to make it compile with the modified stream API …

Stream x improve

---

CHANGELOG.md
Cargo.toml
src/flash.rs

This PR bumps the version of `embedded-storage` to 0.3, the latest version.

Updating to embedded-storage 0.3

---

CHANGELOG.md
Cargo.toml
examples/uart-dma.rs

I created a simple example for using UART with DMA (only on the rx side).
This solves the issue of overrun errors (see #696) when the interrupt handler is not quick enough and data is lost on the input.

create uart-dma.rs example

---

CHANGELOG.md
Cargo.toml
src/gpio/hal_1.rs

it finally happened: the stable release of `embedded-hal` has just been released.

update to `embedded-hal` v1.0.0 (no more RC!)

---

CHANGELOG.md
src/serial/hal_02.rs
src/serial/hal_1.rs
src/serial/uart_impls.rs

The `Serial::new` method cannot be called using a generic `serial::Instance` because the `Instance` trait does not require that the associated `RegisterBlock` implements `RegisterBlockImpl`. See the example below.
```rust
use stm32f4xx_hal::{
gpio::PushPull,
prelude::*,
rcc::Clocks,
serial::{Instance, Serial},
uart::config::InvalidConfig,
};
struct SerialConnection<UartX: Instance>(Serial<UartX, u8>);
fn make_serial<UartX: Instance>(
usart: UartX,
tx: impl Into<UartX::Tx<PushPull>>,
rx: impl Into<UartX::Rx<PushPull>>,
baud_rate: u32,
clocks: &Clocks,
) -> Result<SerialConnection<UartX>, InvalidConfig> {
Serial::<_, u8>::new(usart, (tx, rx), baud_rate.bps(), &clocks)
.map(|conn| SerialConnection(conn))
}
```
This fails to compile with the following error.
```
error[E0277]: the trait bound …
```

Require the RegisterBlock associated with a serial::Instance to implement RegisterBlockImpl

---

CHANGELOG.md
Cargo.toml
src/sdio.rs

Bump sdio-host to 0.9.0, which includes new voltabe_range format for send_op_conditon, generic arguments for registers (SD, EMMC).
Significantly, the SdioPeripheral::get_capacity() method has been replaced with SdioPeripheral::get_address_mode(). This change provides a more intuitive and accurate representation for eMMC cards, which unlike SD cards, do not have a distinction between standard and high capacity variants and uniformly use block addressing. The previous implementation relied on the high capacity bit in the OCR register, which is not applicable to eMMC cards. This bit has been removed in the sdio-host library to reflect the correct specifications for eMMC cards.
Was not tested yet, i don't have eMMC card, but I can test with SD card tomorrow.
(Recreated #733)

Sdio-host: update to 0.9.0, add AddressMode enum

---

CHANGELOG.md
src/i2c/dma.rs

We should set the `last` control bit in I2C when the read length is larger than or equal to 2 and when using DMA in master mode.
Failing to set the `last` bit leads to elusive bugs that will be revealed only when the system is under some stress. In the following example, the I2C and DMA is configured to read 6 bytes from a peripheral.
When the `last` bit is not set, the I2C interface will not respond the peripheral with NACK after receiving the 6th byte, causing the peripheral to continue to transmit the 7th byte. The DMA interrupt, however, will be triggered after receiving the 6th byte. When the system is not under stress, the DMA interrupt will get served promptly. Inside the ISR the I2C `stop` bit will be programed, causing the peripheral to terminate the transmission. Even though the …

Fix transmission termination in I2C DMA master read.

---

CHANGELOG.md
src/i2c.rs
src/i2c/dma.rs

When a stop condition is generated by the I2C DMA ([example](https://github.com/stm32-rs/stm32f4xx-hal/blob/533797526ec093d5c04bad02171cba856e30d20d/src/i2c/dma.rs#L632)), the [code](https://github.com/stm32-rs/stm32f4xx-hal/blob/533797526ec093d5c04bad02171cba856e30d20d/src/i2c/dma.rs#L456-L458) does not wait for the finish of the stop condition. However, the [comments](https://github.com/stm32-rs/stm32f4xx-hal/blob/533797526ec093d5c04bad02171cba856e30d20d/src/i2c/dma.rs#L631) **falsely** indicate that there will be a spin-wait.
The I2C interface can get stuck if a new I2C transmission attempts to start while the previous stop condition is being generated. The new transaction will be inadvertently terminated by the previous stop condition. Subsequently, the I2C interface gets stuck. The …

Prevent starting a new I2C transmission before previous stop finishes.

---

CHANGELOG.md
Cargo.toml
examples/serial-dma.rs
src/prelude.rs
src/serial.rs
src/serial/dma.rs
src/serial/uart_impls.rs
src/uart.rs

The implementation follows existing DMA abstraction for I2C interface.
The implementation has been tested on STM32F407-Discovery board with the code in `examples/serial-dma.rs`.

Implement Serial DMA abstraction.

---

CHANGELOG.md
src/timer/pwm.rs

`set_complementary_polarity` was setting the polarity for the for the primary output instead of the complementary output

fix: complementary output polarity

---

.cargo/config.toml
.github/workflows/ci.yml
.github/workflows/clippy.yml
.github/workflows/rustfmt.yml
.vscode/settings.json
CHANGELOG.md
Cargo.toml
examples/rtic2-tick.rs
src/prelude.rs
src/timer.rs
src/timer/monotonic.rs
src/timer/monotonics.rs

from `rtic-monotonics` for TIMx
Add `rtic2-blink` example
~~Waiting for `rtic-time` 2.0 release~~

Port `rtic-time::Monotonic` implementations

---

CHANGELOG.md
Cargo.toml
examples/ltdc-screen/main.rs
examples/ltdc-screen/screen.rs
src/lib.rs
src/ltdc.rs
src/rcc/enable.rs

Closes #256 
cc @jonasdn @ierturk

port ltdc from f7xx-hal

---

CHANGELOG.md
src/spi.rs

Rebased and optimized version of #566

Allow different lengths of buffers in SpiBus::transfer

---

CHANGELOG.md
Cargo.toml
examples/sai-duplex.rs
src/dma/traits.rs
src/dma/traits/f4.rs
src/gpio/alt/f4.rs
src/lib.rs
src/prelude.rs
src/rcc/f4/enable.rs
src/sai.rs

This PR contains some preliminary code for the SAI. In the stm32f7xx-hal a driver already exists iirc, but that driver is limited to duplex I2S. This API is slightly more flexible, yet similarly easy to use.
Usage example:
```rust
// Initialize clocks.
let rcc = ctx.device.RCC.constrain();
let clocks = rcc
.cfgr
.use_hse(8.mhz())
.saia_clk(172.mhz())
.saib_clk(172.mhz())
.freeze();
// Test that the SAI clock is suitable for 48000KHz audio.
assert!(clocks.saia_clk().unwrap() == 172.mhz().into());
assert!(clocks.saib_clk().unwrap() == 172.mhz().into());
let gpioe = ctx.device.GPIOE.split();
// SAIB is made synchronous to A.
let (saia, saib) = ctx.device.SAI.split_sync_b();
let protocol = Protocol {
sync: Synchronization::I2S,
word_size: 16,
slot_size: 16,
num_slots: 2,
};
let tx = …
```

wip: Serial audio interface (SAI)

---

examples/display-touch.rs
src/fmpi2c.rs
src/fmpi2c/hal_02.rs
src/fmpi2c/hal_1.rs
src/i2c/hal_02.rs
src/prelude.rs

FMPI2c clean

---

CHANGELOG.md
Cargo.toml
README.md
examples/ltdc-screen/screen.rs
src/dsi.rs
src/lib.rs
src/ltdc.rs
src/rcc/f4/enable.rs

Adapted from the stm32h7xx-hal implementation, changed to use register accessor functions and use the RCC enable/reset mechanisms which are different in the stm32f4xx-hal.
Changes the `LtdcPins` argument to the `DisplayController` to be an `Option`, as they aren't used (and aren't needed for DSI interfaces).
Tested on STM32F469I-DISC board, in [this project](https://gitlab.com/mfairman/stm32f469i-disc/-/compare/mfairman%2Fsdram...mfairman%2Fdsi-lcd?from_project_id=60414443&straight=false) (pending various crate updates before that BSP is directly usable)

dsi: add support for DSI host peripheral

---

CHANGELOG.md
Cargo.toml
examples/f469disco-lcd-test.rs
src/dsi.rs

Initializes the LTDC, DSIHOST and OTM8009A to output alternating color / BER patterns.  This does not use a framebuffer so can run without SDRAM.

dsi: add color pattern test for STM32F469I-DISC board

---

src/i2c.rs

I have not verified the change for the 10-bit addresses, but it is likely to suffer the same problem.

I2C read address fix

---

CHANGELOG.md
examples/pwm-dead-time.rs
examples/pwm-input.rs
examples/pwm-sinus.rs
examples/pwm.rs
src/timer.rs
src/timer/hal_02.rs
src/timer/hal_1.rs
src/timer/pwm.rs

The main idea is from https://github.com/stm32-rs/stm32f3xx-hal/pull/34 but with several changes.
Always split PWM on manager and channels.
The main disadvantage is removed `embedded_hal_02::Pwm` as no more `Pwm` struct.
cc @apollolabsdev @kossnikita

move PWM pins connecting after inialization

---

examples/rtic2-tick.rs

Stubbed my toe on this, this PR attempts to make it easier for the next person :)

rtic2-tick: clarify SysTick mono instructions

---

examples/spi-dma.rs

fix: #812
Use DMA1_STREAM4 instead DMA2_STREAM4

Fix interrupt misuse in spi-dma example

---

CHANGELOG.md
src/i2c/dma.rs

Rationale - Blocking access is already exposed via the I2CMasterDma::read + I2CMasterDma::write functions but the embedded_hal::i2c::I2c trait is not implemented meaning it does not integrate well with generic crates.
cc: @shonrb

i2c: Implement embedded_hal::i2c::I2c for I2CMasterDMA
