- src/delay.rs
> Fixed the maximum RVR value when creating a delay.

- src/serial.rs
This is proposed for comments. Assuming it looks ok, I will document and implement onthe other usarts.
> Add a config struct to control uart async data framing

- src/serial.rs
I copied the pattern from the stm32f30x-hal crate.
> Macroify USART1,2,3,6

- .travis.yml
- Cargo.toml
- src/gpio.rs
- src/lib.rs
- src/rcc.rs
- src/serial.rs
- src/spi.rs
- src/timer.rs
> Add HAL implementation for stm32f411xx boards

- src/i2c.rs
The main issue that caused #26 was inconsistent units. Clock is in Hz, Speed is KHz. So things were 1000x off. Masking the variable seems to be the safest way to fix this.
Some other things, it was using the wrong peripheral clock. In standard speed mode, the CCR value is for half of a clock, not 1 whole clock period. * 2 fixes this.
> Fix I2C speed issues

- src/gpio.rs
> OTy is 1 for open drain, not 0

- src/gpio.rs
- src/lib.rs
- src/rcc.rs
- src/serial.rs
- src/spi.rs
- src/timer.rs
Hello there! I have some formatting suggestions you might find useful.
I'm RustyRobot, and my mission is to empower awesome software authors to keep the code clean and formatted.
Common formatting style is crucial for attracting contributors from all over the world.
If you have a rustfmt.toml in your repo, it has already been loaded into my circuits, and I processed your code according to the config.
I'm only learning how to do my job best, and I'd appreciate if you could leave your feedback here:
https://goo.gl/forms/4CdAzeWxWdvGTJus1
_______________
RustyRobot v0.1.0
Author: https://github.com/mersinvald
Sources: https://github.com/mersinvald/rustyrobot
> Formatting Suggestions from RustyRobot

- src/i2c.rs
Straight-forward implementation. Tested on Nucleo F429. Macro-less working as expected 👍
> Add I2C3 support

- src/rcc.rs
- support for HSE
- support for setting AHB, APB1 and APB2 frequency
- code cleanup
> Rcc improvements

- CHANGELOG.md
- Cargo.toml
> Bumped version to 0.3.0

- src/rcc.rs
> rcc: support PLL configuration for HSE < 16 MHz

- src/rcc.rs
> rcc: fix rounding of hclk and pclk divisor

- CHANGELOG.md
- Cargo.toml
> Bump version to 0.5.0 and release it

- src/rcc.rs
> rcc: find best pllm value to get sysclk as close as possible to requested value

- src/rcc.rs
> enable instruction and data cache and instruction prefetch

- CHANGELOG.md
- Cargo.toml
> Bump stm32f4 to 0.10.0

- README.md
inspired by https://github.com/stm32-rs/stm32f1xx-hal/blob/master/README.md
Solves #134.
> README: add setup instructions

- src/adc.rs
- src/rng.rs
- src/spi.rs
- src/timer.rs
> Fix clippy lints

- CHANGELOG.md
- Cargo.toml
- README.md
Also updated the CHANGELOG and the README accordingly
> Use stm32f4 v0.11 and release 0.8.0

- CHANGELOG.md
- examples/timer-periph.rs
- src/timer.rs
Solves #106.
There is code duplication with [timer-syst](https://github.com/stm32-rs/stm32f4xx-hal/blob/master/examples/timer-syst.rs) in the example. I don't know if it can be avoided.
> Implement Cancel trait for Timer<TIM>

- CHANGELOG.md
- Cargo.toml
> Bump version to 0.8.1 and prepare release

- src/dwt.rs
Closes #158 
This commit contains the following changes
* new doc comment on conditions of measuring time with DWT Cycle Counter
(that using Cycle Counter cannot correctly measure time of tasks that take longer than `u32::MAX`)
* minor changes to doc comments to improve visual formatting
Thank you for reviewing this PR 👍
> doc comment updates for 'src/dwt.rs'

- Cargo.toml
- examples/analog-stopwatch-with-spi-ssd1306.rs
- examples/rng-display.rs
- examples/ssd1306-image.rs
- examples/stopwatch-with-ssd1306-and-interrupts.rs
- src/dwt.rs
https://github.com/stm32-rs/stm32f4xx-hal/pull/161
> reformat it, add an example entry to Cargo.toml

- CHANGELOG.md
- Cargo.toml
> Prepare 0.8.2 release

- CHANGELOG.md
- Cargo.toml
- src/sdio.rs
Various cleanups, 
The biggest change is that Cmd and command related functionality moved to the sdio-host crate.
> Sdio driver updates

- src/serial.rs
This adds the missing `blocking::serial::Write` implementation as
discussed in #184.
Closes #184.
> Implement `blocking::serial::Write` for `Tx` and `Serial` types

- src/rcc.rs
> Move maximum clock frequencies into public constants

- src/time.rs
Matches f1xx, h7xx, probably other HALs.
> Derive Debug for times

- CHANGELOG.md
- src/adc.rs
- src/dac.rs
- src/gpio.rs
- src/i2c.rs
- src/qei.rs
- src/serial.rs
- src/spi.rs
- src/timer.rs
> Use bitbanding to avoid data races

- Cargo.toml
- examples/analog-stopwatch-with-spi-ssd1306.rs
- examples/rng-display.rs
- examples/ssd1306-image.rs
- examples/stopwatch-with-ssd1306-and-interrupts.rs
> Bump ssd1306 dev dependency to 0.4 and updated examples

- src/sdio.rs
Add support for SCSD cards in the SDIO interface
Added the timeout since setting the bus width and frequency was timing out because the card was not ready.
> Add support for SCSD cards with SDIO

- src/rcc.rs
I am porting a C firmware that slightly overclocks the following values on an stm32f439.
* SYSCLK 192MHz (max 180MHz)
* APB1/PCLK1/PPRE1_register 48Mhz (max 45MHz)
* APB2/PCLK2/PPRE2_register 96Mhz (max 90MHz)
I need to maintain these clock speeds in the rust port, so my usage will look like this:
```rust
let clocks = unsafe {
rcc.cfgr
.use_hse(4.mhz())
.sysclk(192.mhz())
.hclk(192.mhz())
.pclk1(48.mhz())
.pclk2(96.mhz())
.sysclk_allow_overclock()
.pclk1_allow_overclock()
.pclk2_allow_overclock()
.freeze()
};
```
Would love to hear suggestions for better naming of the builder method names.
> Implement unsafe overclocking safety overrides

- CHANGELOG.md
- Cargo.toml
> cargo: update bxcan to latest version

- CHANGELOG.md
- src/adc.rs
- src/can.rs
- src/dac.rs
- src/dma/traits.rs
- src/gpio.rs
- src/i2c.rs
- src/otg_fs.rs
- src/otg_hs.rs
- src/pwm.rs
- src/qei.rs
- src/rcc/mod.rs
- src/rng.rs
- src/rtc.rs
- src/sdio.rs
- src/serial.rs
- src/spi.rs
- src/syscfg.rs
- src/timer.rs
> Add DSB to fix ST erratum 2.1.13

- CHANGELOG.md
- src/qei.rs
- allows use of new function for any timer
- deprecates timX functions
> qei: implement generics

- CHANGELOG.md
- Cargo.toml
- src/dma/mod.rs
- src/dma/traits.rs
- src/i2c.rs
- src/rtc.rs
> Bump stm32f4 dependency to 0.13 and adjust code to compile

- CHANGELOG.md
- Cargo.toml
> Bump main crate dependencies

- CHANGELOG.md
- Cargo.toml
> Bump rand_core dependency

- CHANGELOG.md
- Cargo.toml
- examples/analog-stopwatch-with-spi-ssd1306.rs
- examples/delay-blinky.rs
- examples/pwm.rs
- examples/qei.rs
- examples/rng-display.rs
- examples/serial.rs
- examples/ssd1306-image.rs
- examples/stopwatch-with-ssd1306-and-interrupts.rs
- examples/timer-periph.rs
- examples/timer-syst.rs
> Bump ssd1306 dev-dependency and cleanup examples

- CHANGELOG.md
- README.md
> Update README.md with up-to-date information

- CHANGELOG.md
- src/timer.rs
> Eliminate macro warnings caused by PWM change

- CHANGELOG.md
- src/gpio.rs
> Downgrade2

- CHANGELOG.md
- Cargo.toml
- README.md
- examples/delay-syst-blinky.rs
- examples/delay-timer-blinky.rs
- src/delay/mod.rs
- src/delay/syst.rs
- src/delay/timer.rs
Slightly improved and rebased #309
> Timer delay

- CHANGELOG.md
- examples/analog-stopwatch-with-spi-ssd1306.rs
- examples/rtic.rs
- examples/stopwatch-with-ssd1306-and-interrupts.rs
- src/gpio.rs
> Use CamelCase for gpio::Edge enum variants

- CHANGELOG.md
- src/gpio/convert.rs
Code from `stm32l0xx-hal` partially used.
> Temporary change pin mode

- CHANGELOG.md
- Cargo.toml
- examples/ist7920_bidi_normal_spi.rs
- src/spi.rs
Add bidirectional mode for spi. As previous pr #210 this pr provide bidi mode for spi but more confidence and feature full.
> Add bidirectional mode for spi

- CHANGELOG.md
- Cargo.toml
- examples/analog-stopwatch-with-spi-ssd1306.rs
- examples/rng-display.rs
- examples/ssd1306-image.rs
- examples/ws2812_spi.rs
> Bumped some dependencies and fixed example fallout

- CHANGELOG.md
- src/gpio.rs
Adds implementations of IoPin for 
- `Output<PushPull>> <-> Input<PullUp>>`
- `Output<PushPull>> <-> Input<PullDown>>`
> IoPin` for `Output<PushPull>> <-> Input<PullUp>> and Input<PullDown>>

- examples/serial.rs
> Fix overflow in example

- CHANGELOG.md
- src/dma/traits.rs
> Added the missing DMA implementations for USART3 (rebased)

- CHANGELOG.md
- Cargo.toml
- examples/rtc.rs
- src/rtc.rs
Ported from f7xx-hal
cc @systec-ms
> Use time instead of rtcc, add rtc-example

- CHANGELOG.md
- Cargo.toml
- src/adc.rs
- src/delay/hal_1.rs
- src/delay/mod.rs
- src/dwt.rs
- src/fmpi2c.rs
- src/fmpi2c/hal_1.rs
- src/fugit/hal_1.rs
- src/fugit/mod.rs
- src/gpio.rs
- src/gpio/hal_1.rs
- src/i2c.rs
- src/i2c/hal_1.rs
- src/pwm.rs
- src/qei.rs
- src/serial.rs
- src/serial/hal_1.rs
- src/spi.rs
- src/spi/hal_1.rs
Same as #388, but uses alpha.7
> e-hal alpha.7

- CHANGELOG.md
- src/spi/hal_1.rs
per #445, i don't have a moment to look at the I2C at the moment as the behaviour is a bit more complex wrt. where starts and ends get asserted.
> Added transactional SPI implementation

- CHANGELOG.md
- examples/analog-stopwatch-with-spi-ssd1306.rs
- examples/rtic.rs
- examples/stopwatch-with-ssd1306-and-interrupts.rs
- src/gpio.rs
- src/gpio/alt.rs
- src/gpio/convert.rs
- src/gpio/dynamic.rs
- src/gpio/erased.rs
- src/gpio/hal_02.rs
- src/gpio/hal_1.rs
- src/gpio/partially_erased.rs
- src/serial.rs
> Pin::into_mode

- CHANGELOG.md
- src/gpio/convert.rs
Same as https://github.com/stm32-rs/stm32h7xx-hal/pull/359
> fix with_mode

- CHANGELOG.md
- Cargo.toml
- src/prelude.rs
- src/timer/monotonic.rs
- src/timer/pwm.rs
r? @therealprof 
should I enable `rtic` feature by-default / remove it ?
> SysMonoTimerExt

- CHANGELOG.md
- src/timer.rs
Second try to get issue #501 fixed.
> Addressing issue #501 with start_pwm

- CHANGELOG.md
- src/timer/pwm.rs
See https://github.com/stm32-rs/stm32f1xx-hal/pull/434
> fix PwmHz::get_period

- CHANGELOG.md
- src/timer.rs
- src/timer/delay.rs
> Improve docs for Delay

- CHANGELOG.md
- src/dma/mod.rs
- src/prelude.rs
- src/serial.rs
please see the individual commit messages for further details.
i've tested this on an STM32F401.
this solves #550.
> offer `clear_idle_interrupt` from `serial::Rx` in DMA `Transfer`

- CHANGELOG.md
- src/gpio/alt.rs
> Fix alternate function pin definitions for FMPI2C1

- CHANGELOG.md
- Cargo.toml
- README.md
> release 0.15

- CHANGELOG.md
- examples/pwm-dead-time.rs
- src/timer/pwm.rs
Advanced PWM dead time insertion example.
> Example dead time2

- CHANGELOG.md
- src/dma/traits.rs
- src/fmpi2c.rs
- src/fmpi2c/hal_1.rs
- src/gpio/alt.rs
- src/lib.rs
- src/prelude.rs
- src/serial/config.rs
- src/serial/uart_impls.rs
- src/uart.rs
> split USART and UART impls

- src/gpio/alt.rs
#610 was missed during #611 rebase
> fix rebase 610

- CHANGELOG.md
- src/spi.rs
> Fix mstr bit for SPI Master/Slave

- CHANGELOG.md
- src/spi.rs
> map `$SpiSlave` to `SpiSlave` struct

- .vscode/settings.json
- CHANGELOG.md
- src/rtc.rs
Fixes #659 
defmt removed on `AlarmDay` until https://github.com/knurling-rs/defmt/issues/763
> fix defmt compilation

- CHANGELOG.md
- Cargo.toml
- src/spi/hal_1.rs
see [their changelog][eh-changelog] for further details.
[eh-changelog]: https://github.com/rust-embedded/embedded-hal/blob/v1.0.0-alpha.11/embedded-hal/CHANGELOG.md
> update to `embedded-hal=1.0.0.alpha-11`

- CHANGELOG.md
- src/timer/counter.rs
related to https://github.com/stm32-rs/stm32f1xx-hal/pull/449
> reset timer interrupt in Counter::start

- CHANGELOG.md
- src/qei.rs
- src/timer.rs
and `.write_count()` for TIM
will close #676
> `.set_count()` for qei

- CHANGELOG.md
- src/spi.rs
> Spi revert

- CHANGELOG.md
- Cargo.toml
- src/gpio/hal_1.rs
see their [changelog] for further details.
[changelog]: https://github.com/rust-embedded/embedded-hal/blob/master/embedded-hal/CHANGELOG.md#v100-rc3---2023-12-14
> update to `embedded-hal=1.0.0-rc.3`

- CHANGELOG.md
- Cargo.toml
- build.rs
- src/i2s.rs
- src/lib.rs
- src/prelude.rs
> device-selected to build.rs

- src/i2c.rs
This commit brings back the while-loop waiting at the end of the blocking read/write methods on I2C. The while-loop waiting is necessary to ensure that the I2C interface has become idle before returning from the blocking read/write methods.
As an example, the following code might break without the while-loop waiting. Assuming that `handle` is a DMA handle to an I2C interface. After the first write method returns, without the while-loop waiting, the I2C interface can be generating the stop condition when the code reaches the second `write` method, which then fails the busy test `self.busy_res()?` and causes the second `write` to return `WouldBlock`.
```
handle.write(addr, buf); // Ok(())
handle.write(addr, buf); // Err(WouldBlock)
```
The added while-loop affects only the blocking methods …
> Let I2C blocking methods wait until STOP is sent.

- CHANGELOG.md
- examples/rtc_alarm.rs
- src/rtc.rs
This allows a minimum time of 122µs and a maximum time of 32s, with a resolution of 61µs
> RTC: Use RTCCLK for Wakeup timer when period is <32s

- CHANGELOG.md
- src/fsmc_lcd/display_interface_impl.rs
- src/fsmc_lcd/mod.rs
- src/fsmc_lcd/pins.rs
> support FMC u8 data width

- CHANGELOG.md
- src/serial/config.rs
- src/serial/uart_impls.rs
> add IrDA SIR mode support to the usart code

- CHANGELOG.md
- Cargo.toml
- src/serial/hal_1.rs
> initial embedded-io support

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- examples/rtic2-tick.rs
- src/timer/monotonics.rs
See https://github.com/rtic-rs/rtic/pull/960
> monotonics fix: CC1 instead of CC3

- CHANGELOG.md
- src/spi.rs
> Clean SPI write impls

- CHANGELOG.md
- src/i2c.rs
- src/i2c/common.rs
- src/i2c/hal_1.rs
Needs tests with 10-bit I2C address devices!!!
> I2C 10-bit address support

- CHANGELOG.md
- Cargo.toml
> fix defmt dependency enabling

- CHANGELOG.md
- src/timer/monotonics.rs
Related https://github.com/rtic-rs/rtic/pull/984
> fix monotonics
